name: .NET test Cosmos extension with Cosmos DB Emulator
on:
    workflow_dispatch:
jobs:
  unit_tests:
    name: Test Cosmos extension with Cosmos DB Emulator
    runs-on: windows-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Start Azure Cosmos DB emulator
        run: |
          Write-Host "Launching Cosmos DB Emulator"
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator
      - name: Run .NET tests
        run: dotnet test -graphBuild:True  .\Extensions\Cosmos\Cosmos.DataTransfer.CosmosExtension.UnitTests\
